pipeline {
    agent any

    stages {
        stage("Clean Up") { // Deletes previous build directories. Good practice at the begining of job
            steps {
                dir("${WORKSPACE}"){
                sh """
                rm -rf simple_cpp_app*
                """
        }
            }
        }

        # stage('Clone Repository') {
        #     steps {
        #         // Define the repository URL
        #         script {
        #             def repoUrl = 'https://github.com/sarathelayadath/simple_cpp_app.git'
        #             echo "Cloning repository from ${repoUrl}"
        #             git branch: 'main', url: repoUrl
        #         }
        #     }
        # }

        # stage('Build') {
        #     steps {
        #         dir("${WORKSPACE}") {
        #             sh """
        #             echo "Start building"
        #             make
        #             """
        #         }
        #     }
        # }

        # stage('Test') {
        #     steps {
        #         dir("${WORKSPACE}") {
        #             sh "./file_exists"
        #         }
        #     }
        }
    }

    post {
        success {
            echo 'Pipeline successful!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}          
