pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Define the repository URL
                script {
                    def repoUrl = 'https://github.com/sarathelayadath/simple_cpp_app.git'
                    echo "Cloning repository from ${repoUrl}"
                    git branch: 'main', url: repoUrl
                }
            }
        }

        // Add more stages for building, testing, etc., as needed
    }

    post {
        success {
            echo 'Pipeline successful!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
